### ISSUE TITLE
Sequelize db table errors (models or migrations?)

### ISSUE THREAD

**Issue by qodesmith** [qodesmith/qodesmith-website#1]
Gentlemen,

I've successfully created migrations and models and have migrated (m.m.m.?). Anyway, I'm getting an error that most likely has to do with my relationships. Here's the error:

`Unhandled rejection SequelizeDatabaseError: column posts.category_id does not exist`

The error changes depending on how I tweak things, so I'm going to have to show someone in person what's going on. I've googled a ton of manure to come up empty handed. At first, the error was a snake-case thing where it was looking for a snake-cased column, but all my columns are underscored. Then I went through the trouble of adding `underscored: true` to every model, changed all the `createAt`'s to `create_at`, etc., dropped, re-migrated... no dice.

I'd like to look over this with someone and trace the trail back to discover what the error is. I've checked my associations and they look legit. I've since moved on to other tasks to keep going, but I'm at a serious handicap without being able to check my routes and do database stuff. Thanks guys.

**Comment by qodesmith** [comment]
Totally forgot to @ you gaiz...
@DrRobotmck @bigtone1284 @WilliamfShaw @harimohanraj89 @h4w5

**Comment by DrRobotmck** [comment]
- When does this error occur?
- Have you checked your database through postgres to make sure your tables have the proper columns?
- what type of relationship are you attempting to set up between a post and category?

**Comment by qodesmith** [comment]
The error occurs when I try to visit a route, e.g. `localhost:3000/users`.
In postgres, all tables are there and named as they should be.
The issue isn't exclusive to post and category. Depending on the route that I hit, it will give a similar error. I have a few tables with multiple relationships: some 1 to many, others many to many.

**Comment by qodesmith** [comment]
Post and category have a many to many relationship.

**Comment by DrRobotmck** [comment]
Check the associations that you are defining in your models. They look a little odd.

**Comment by qodesmith** [comment]
Checking now... Was the `underscored: true` thing necessary? I feel like no, but I tried anyway.

**Comment by DrRobotmck** [comment]
its not a bad idea to have that there

**Comment by qodesmith** [comment]
From the docs it looks like many to many relationships don't have a foreign key specified. I removed the foreign keys in both posts and categories (just to test), and still no dice. Is there something else you're seeing or am I close with the foreign key thing?

**Comment by DrRobotmck** [comment]
Take a look at the bloggr_app solution

**Comment by qodesmith** [comment]
Ok, I edited a few things and have a different error (my original error).
My categories associations:
`        categories.belongsToMany(models.posts, {through: 'categories_posts', foreign_key: 'post_id'});
`

My posts associations (I've removed all others just to test with posts & categories):
`        posts.belongsToMany(models.categories, {through: 'categories_posts', foreign_key: 'category_id'});
`

This returns the error:
`Unhandled rejection SequelizeDatabaseError: column posts.tagId does not exist`
This was the whole reason I went and did the whole `underscored: true` thing, to avoid sequelize from looking for a snake-cased column.

**Comment by qodesmith** [comment]
Crap, wait a minute... give me a sec...

**Comment by qodesmith** [comment]
Do my migrations for the join tables (categories-posts) need the `created_at` / `updated_at` columns? I took those out, just changed my models, and now I have this error:
`Unhandled rejection SequelizeDatabaseError: column posts.categories_posts.created_at does not exist`

Should I update the migrations to have those columns, drop the db, and re-migrate?

**Comment by DrRobotmck** [comment]
set timestamps false on that model, like we did previously in class

**Comment by qodesmith** [comment]
YES! The answer was yes. I didn't it anyway and it worked. Now on editing all my models and making sure all the associations are working.

What I learned here was that in a many-to-many relationship, you don't need to include a `hasMany` declaration.

**Comment by qodesmith** [comment]
Ahhhh, so I DIDN'T need the timestamps, I just needed to set them to false at the model level. Much cleaner that way. This is huge for me right now! Thanks bro.

**Comment by qodesmith** [comment]
Wait, one more thing... I noticed that in the blogger example we don't have models for our join tables. Is that normal? In my current project I created those models.

**Comment by DrRobotmck** [comment]
you do not, but it can be useful to have a model for certain situations. If you have it no problem, likewise if you don't no problem.

**Comment by qodesmith** [comment]
My life can now proceed. You rule. As a quick side-note, I've been trying to get a contact form going. Sending emails through node has proved difficult (without having to tweak my gmail account). Should I / can I open an issue for that?

**Comment by DrRobotmck** [comment]
sure. i'm gonna close this.
